site_name: Regelgeving
site_author: 'Eindhoven City'
theme:
  name: material
  logo: images/ehcity.png
  favicon: images/favicon.ico 
  
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share

# CSS
extra_css:
  - stylesheets/extra.css

# Copyright
copyright: Copyright &copy; 2025 Eindhoven City